// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used only by the Prisma CLI (migrate / introspect). Prefer the direct,
    // unpooled connection here so migrations don't run through a pooler; fall
    // back to the pooled URL when a direct one isn't configured. The runtime
    // client reads `DATABASE_URL` separately (see src/lib/db.ts).
    url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"]!,
  },
});
